def broken_function(message):
	raise Exception(message)
